import React, { useRef, memo } from "react";
import Markdown from "@components/Markdown.js";
import rehypeHighlight from "rehype-highlight";
import { visit, SKIP } from "unist-util-visit";
import { defaultSchema } from "rehype-sanitize";

function ChatDisplay({
  outerClassName = "",
  innerClassName = "",
  messages,
  assistantRef,
  setShowDiscover,
}) {
  const ref = useRef(null);

  let scrollToBottom = false;
  if (!ref.current) {
    //messages are not open, we want to scroll to bottom when they are opened
    scrollToBottom = true;
  } else if (
    ref.current.scrollHeight - ref.current.clientHeight <=
    ref.current.scrollTop + 1
  ) {
    //already at the bottom so scroll to bottom once new message is added
    scrollToBottom = true;
  }

  let handleContinue;
  const promptToContinue = messages[messages.length - 1]?.promptToContinue;
  if (promptToContinue) {
    handleContinue = () => {
      assistantRef.current.handleInput({
        messages,
        continueSystemPrompt:
          messages[messages.length - 1].continueSystemPrompt,
      });
    };
  }

  return (
    <div ref={ref} className={`overflow-y-auto ${outerClassName}`}>
      <div className={`mb-4 flex flex-col gap-5 ${innerClassName}`}>
        {messages.map((message, i) => (
          <Message
            key={i}
            message={message}
            onComplete={
              scrollToBottom && i === messages.length - 1
                ? () => {
                    ref.current.scrollTop = ref.current.scrollHeight;
                  }
                : undefined
            }
            setShowDiscover={setShowDiscover}
            assistantRef={assistantRef}
          />
        ))}
        {promptToContinue && (
          <button
            ref={(el) => {
              if (el && scrollToBottom) {
                ref.current.scrollTop = ref.current.scrollHeight;
              }
            }}
            className="self-center rounded-xl border-2 border-stone-500 bg-stone-100 px-4 py-1 font-bold hover:bg-stone-200"
            onClick={handleContinue}
          >
            {promptToContinue}
          </button>
        )}
      </div>
    </div>
  );
}

const messageStyle = "prose prose-stone mx-3 max-w-full ";
const assistantMessageStyle = messageStyle;
const userMessageStyle =
  messageStyle + "bg-stone-100 border border-stone-500 rounded-lg px-2 py-1";

const assistantMessageContainerStyle = "group";
const userMessageContainerStyle = "self-end max-w-[80%]";

const Message = memo(function Message({
  message,
  onComplete,
  setShowDiscover,
  assistantRef,
}) {
  const formattedMessage = formatMessage(message);
  if (!formattedMessage) return null;

  const handleClick = (e) => {
    try {
      const link = e.target.closest("a");
      if (link?.href) {
        e.preventDefault();
        requestOpenUrl(link.href);
        return;
      }
      if (!message.welcome) return;
      const button = e.target.closest("button");
      const action = button?.dataset?.action;
      if (!action) return;
      if (action === "discover") {
        setShowDiscover(true);
      } else if (action.startsWith("open-")) {
        const app = action.slice("open-".length);
        //const maxCost = await getMinCost(app); //save a request
        assistantRef.current.handleApp({
          app,
          maxCost: message.welcomeMinCost,
        });
      } else {
        throw new Error(`Unknown action: ${action}`);
      }
    } catch (error) {
      console.error(error);
      assistantRef.current.toastsRef.current.addToast(
        "An unexpected error occurred",
        "error",
      );
    }
  };

  return (
    <div
      className={
        message.role === "user"
          ? userMessageContainerStyle
          : assistantMessageContainerStyle
      }
      onClick={handleClick}
    >
      <Markdown
        className={
          message.role === "user" ? userMessageStyle : assistantMessageStyle
        }
        remarkPlugins={remarkPlugins}
        rehypePlugins={
          message.welcome
            ? [...rehypePlugins, rehypeWelcomeButton]
            : rehypePlugins
        }
        rehypeSanitizeOptions={
          message.welcome ? welcomeRehypeSanitizeOptions : rehypeSanitizeOptions
        }
        onComplete={onComplete}
      >
        {formattedMessage}
      </Markdown>
      {message.model && (
        <i className="-mb-4 hidden pl-3 text-xs text-stone-600 group-hover:block">
          {`Generated by ${message.model}`}
        </i>
      )}
    </div>
  );
});

function formatMessage(message) {
  if (message.role === "system") return "";
  const tagsToInclude = {
    user: new Set(["user_request"]), //exclude suggested_apps, app_context, user_highlighted_text, logs
    assistant: new Set([undefined, "intermediate_script", "final_script"]), //exclude open_app
    display: new Set([undefined]),
  };
  const messageTagsToInclude = tagsToInclude[message.role];
  return message.tags
    .filter((tag) => messageTagsToInclude.has(tag.tag))
    .map(formatTag)
    .join("");
}

function formatTag({ tag, content }) {
  if (tag === "intermediate_script" || tag === "final_script") {
    return `~~~magicscript\n${content.trim()}\n~~~`;
  } else if (tag === "user_request") {
    //improve markdown formatting by replacing single line breaks with double line breaks
    return content.trim().replace(/([^\n])\n(?!\n)/g, "$1\n\n");
  }
  return content;
}

function remarkHtmlToText() {
  return (tree) => {
    visit(tree, (node) => {
      if (node.type === "html") {
        node.type = "text";
      }
    });
  };
}

const preStyle =
  "not-prose text-sm bg-stone-50 border border-stone-500 rounded-md overflow-x-auto px-2 py-2";

function rehypeCode() {
  return (tree) => {
    visit(tree, "element", (node) => {
      if (
        node.tagName === "pre" &&
        node.children.length === 1 &&
        node.children[0].tagName === "code"
      ) {
        const code = node.children[0];
        if (code.properties.className?.includes("language-magicscript")) {
          code.properties.className = ["language-javascript"]; //fix class name for highlighting
          const pre = { ...node }; //clone node since we mutate it below
          pre.properties.className = [preStyle];
          //now make code block collapsible
          const summary = {
            type: "element",
            tagName: "summary",
            children: [{ type: "text", value: "Executing Script..." }],
          };
          node.tagName = "details";
          node.properties = {};
          node.children = [summary, pre];
        } else {
          //not collapsible, just style pre
          node.properties.className = [preStyle];
        }
        return SKIP; //don't traverse children
      }
    });
  };
}

const welcomeButtonStyle = "underline";

function rehypeWelcomeButton() {
  return (tree) => {
    visit(tree, "element", (node) => {
      if (
        node.tagName === "a" &&
        node.properties.href?.startsWith("?action=")
      ) {
        node.tagName = "button";
        node.properties.className = [welcomeButtonStyle];
        node.properties["data-action"] = node.properties.href.slice(
          "?action=".length,
        );
      }
    });
  };
}

const remarkPlugins = [remarkHtmlToText];
const rehypePlugins = [rehypeCode, rehypeHighlight];
const rehypeSanitizeOptions = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    span: [...(defaultSchema.attributes?.span || []), ["className", /^hljs-./]],
    pre: [...(defaultSchema.attributes?.pre || []), ["className", preStyle]],
  },
};
const welcomeRehypeSanitizeOptions = {
  ...rehypeSanitizeOptions,
  tagNames: [...rehypeSanitizeOptions.tagNames, "button"],
  attributes: {
    ...rehypeSanitizeOptions.attributes,
    button: ["data-action", ["className", welcomeButtonStyle]],
  },
};

export { ChatDisplay, formatMessage };
