export const globals = {
  assistant: false,
  requestApp: false,
  requestFunction: false,
  requestPutData: false,
  requestDeleteData: false,
  requestGetData: false,
  requestGetAllData: false,
  requestGetAllKeysData: false,
  requestFetch: false,
  requestOpenUrl: false,
  requestPublish: false,
  requestDownload: false,
  requestUrlParams: false,
  requestSandbox: false,
};
